### ISSUE TITLE
Exception : Not a GL2 implementation

### ISSUE THREAD

**Issue by satirebird** [brandonborkholder/mirur#10]
Starting the eclipse plugin failed due to an exception. The console log of eclipse shows several error messages when I try to open the Mirur Painter.

Log output:

libEGL warning: failed to create a pipe screen for i965
SWTAccessor.<init>: GTK Version: 2.8.7
Info: GLDrawableHelper.reshape: pre-exisiting GL error 0x500
Exception in thread "main-SWTDisplay-.x11_:0-1-EDT-1" org.eclipse.swt.SWTException: Failed to execute runnable (javax.media.opengl.GLException: Caught GLException: Not a GL2 implementation on thread main)
at org.eclipse.swt.SWT.error(SWT.java:4441)
...
Caused by: javax.media.opengl.GLException: Not a GL2 implementation
at jogamp.opengl.gl4.GL4bcImpl.getGL2(GL4bcImpl.java:37071)
at com.metsci.glimpse.painter.base.GlimpsePainterImpl.paintTo(GlimpsePainterImpl.java:100)

The environment:
Thinkpad T420i
Intel Core i3-2370M
Linux 14.04 LTS

**Comment by brandonborkholder** [comment]
What's your graphics card?

Issue is probably that I need to request a GL2 implementation for the painter.  I'll make the change and find out how to get you a new plugin to test.  I don't have a similar setup.

**Comment by satirebird** [comment]
It's the onboard graphics of the Sandybridge CPU HD 3000
glxinfo reports:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.1 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30

**Comment by brandonborkholder** [comment]
I checked in a fix to explicitly request a GL2 profile as ee7a3a71.

If you don't have the eclipse tools to compile, I have a temporary copy of the repository here https://temp-share.com/f/rwktjouanr  If that works, then I'll release 1.0.2 with the fix.

**Comment by satirebird** [comment]
The behavior is an other, but now I get a NullPointerException:

Eclipse log file:
....
!ENTRY mirur.mirur-ui 1 0 2015-09-25 09:31:37.685
!MESSAGE 09:31:37    INFO: main - GLCapabilityEventListener.logGLExtensions: OpenGL extension found: GL_EXT_shader_integer_mix

!ENTRY org.eclipse.ui.workbench 4 2 2015-09-25 09:33:50.586
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
    at mirur.plugin.VariableSelectListener.install(VariableSelectListener.java:74)
    at mirur.plugin.VariableSelectionModel.addArrayListener(VariableSelectionModel.java:53)
    at mirur.plugin.SelectListenerToggle.add(SelectListenerToggle.java:113)
    at mirur.plugin.SelectListenerToggle.partVisible(SelectListenerToggle.java:103)
    at org.eclipse.ui.internal.WorkbenchPage$26.run(WorkbenchPage.java:5114)
...

I have tried to import the plugin project to eclipse, but it fails due to several problem. First on is the missing dependency of glg2d-0.4-SNAPSHOT. I play a little bit more with this when I have time

**Comment by brandonborkholder** [comment]
Can you send me your entire error log?

It seems to complain that it can't find the Java Variables view.  Which version and package of Eclipse are you running?

**Comment by brandonborkholder** [comment]
Fixed with ee7a3a71 and b055c088
